name: Go Build
on: [ push, pull_request ]
permissions:
  checks: write

jobs:
  test-1_25:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      upload-results: true
      go-version: 1.25
  test-1_26:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      upload-results: true
      go-version: 1.26
